stages:
  - verify
  - build
  - test

# Cache node modules, npm install will take care of minor updates
cache:
  untracked: false
  policy: pull-push
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

include:
  - project: acrolinx/integrations/gitlab-ci-templates
    ref: master
    file: 'npm/check-licenses-gitlab.yml'

vulnerabilities-check:
  stage: verify
  image: node:latest
  before_script:
    - npm ci
  script:
    - npm audit --production --audit-level=moderate
  only:
    - merge_requests
    - master

sonarcloud-check:
  stage: verify
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
