stages:
  - verify
  - build
  - test
  - deploy

# Cache node modules, npm install will take care of minor updates
cache:
  untracked: false
  policy: pull-push
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

include:
  - project: acrolinx/integrations/gitlab-ci-templates
    ref: master
    file: 'npm/check-licenses-gitlab.yml'

vulnerabilities-check:
  stage: verify
  image: node:latest
  before_script:
    - npm ci
  script:
    - npm audit --production --audit-level=moderate
  only:
    - merge_requests
    - master

sonarcloud-check:
  stage: verify
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master

npm-deploy:
  image: node:latest
  stage: deploy
  before_script:
    - node --version
    - npm i
    - npm run buildDistWithNPMLinuxOnly
  script:
    - |
      if [[ $NPM_TOKEN ]]; then
        npm publish --access public
      fi
  only:
    - tags

# maven-deploy:
#   image: maven:3.6-jdk-11
#   stage: deploy
#   before_script:
#     - mkdir -p tmp/s3/v14
#     - cp -r tmp/dist tmp/s3/v14/dev
#     - chmod +x ./gitlab-build-ci.sh
#   script:
#     - ./gitlab-build-ci.sh
#   only:
#     - tags



