stages:
  - verify
  - build
  - deploy

# Cache node modules, npm install will take care of minor updates
cache:
  untracked: false
  policy: pull-push
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

include:
  - project: acrolinx/integrations/gitlab-ci-templates
    ref: master
    file: 'npm/check-licenses-gitlab.yml'

vulnerabilities-check:
  stage: verify
  image: node:latest
  before_script:
    - npm ci
  script:
    - npm audit --production --audit-level=moderate
  only:
    - merge_requests
    - master
    - tags

sonarcloud-check:
  stage: verify
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [ "" ]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - tags

build:
  stage: build
  image: node:latest
  before_script:
    - apt update -y
    - apt upgrade -y
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome-stable_current_amd64.deb
  script:
    - node --version
    - npm ci
    - npm run buildDistWithNPMLinuxOnly
  artifacts:
    paths:
      - tmp/
      - dist/
      - node_modules/
  only:
    - merge_requests
    - master
    - tags

npm-deploy:
  image: node:16-alpine
  stage: deploy
  variables:
    NPM_TOKEN: ${NPM_TOKEN}
  script:
    - echo ${NPM_TOKEN}
    - npm --version
    - npm config set registry=https://registry.npmjs.org/
    - npm config set @acrolinx:registry=https://registry.npmjs.org/
    - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
    - npm ci
    - npm publish --verbose --access public
  only:
    - tags


## Beta release stage for DITA POC
npm-deploy-beta:
  image: node:16-alpine
  stage: deploy
  variables:
    NPM_TOKEN: ${NPM_TOKEN}
  script:
    - echo ${NPM_TOKEN}
    - npm --version
    - npm config set registry=https://registry.npmjs.org/
    - npm config set @acrolinx:registry=https://registry.npmjs.org/
    - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
    - npm ci
    - npm run buildDistWithNPMLinuxOnly
    - npm publish --verbose --access public --beta
  only:
    - DITA_POC

maven-deploy-snapshot:
  image: maven:3.6-jdk-11
  stage: deploy
  variables:
    STAGE: "snapshot"
  before_script:
    - mkdir -p tmp/s3/v14
    - cp -r tmp/dist tmp/s3/v14/dev
    - chmod +x ./gitlab-build-ci.sh
  script:
    - ./gitlab-build-ci.sh
  only:
    - master

maven-deploy-release:
  image: maven:3.6-jdk-11
  stage: deploy
  variables:
    STAGE: "release"
  before_script:
    - mkdir -p tmp/s3/v14
    - cp -r tmp/dist tmp/s3/v14/dev
    - chmod +x ./gitlab-build-ci.sh
  script:
    - ./gitlab-build-ci.sh
  only:
    - tags




