stages:
  - build
  - publish

default:
  tags:
    - dev-cloud

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sonarcloud-check:
  stage: build
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: '0'
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner

build:
  stage: build
  image: node:lts
  before_script:
    - npx playwright install
    - npx playwright install-deps > /dev/null
  script:
    - npm ci
    - npm run lint:check
    - npm run format:check
    - npm run build
    - npm run test
  artifacts:
    paths:
      - dist
    reports:
      junit:
        - js-junit.xml

publish:
  image: node:20-alpine
  when: manual
  stage: publish
  variables:
    NPM_TOKEN: ${NPM_TOKEN}
  script:
    - npm --version
    - npm config set registry=https://registry.npmjs.org/
    - npm config set @acrolinx:registry=https://registry.npmjs.org/
    - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
    - npm ci
    - npm publish --verbose --access public
